---
title: "Beginning_Table"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#This Rnotebook shows the code that enabled to utilize the ggmap package to find the location coordinates for the various locations in our data. To stay under the max daily amount for free ggmap usage, I had to utilize the unique function and then apply its results to the data set as a whole. I then combined that data to our original data set titled, Ebola_data

```{r}

library(ggplot2)
library(dplyr)
 
```
```{r}

cases_death_by_district_and_date_2_ <- read.csv("~/ebola-epidemic/cases_death_by_district_and_date(2).csv", stringsAsFactors=FALSE)

 
```

```{r}
EbolaGDP <- read.csv("~/ebola-epidemic/final_ebola (1).csv")
```


```{r}

uniquetest <- unique(cases_death_by_district_and_date_2_$Localite) 


```
 

```{r}

library(ggmap)


```

```{r}
raw_coord <- geocode(uniquetest)

```

```{r}
unique_column <- matrix(uniquetest, nrow = 122, ncol = 1)
```
```{r}
location_coord = data.frame(city = unique_column,                              lat = raw_coord$lat, lon = raw_coord$lon)
```

```{r}
row.names(location_coord) <-location_coord$city
```

```{r}
cases_death_by_district_and_date_2_$long <- location_coord[cases_death_by_district_and_date_2_$Localite, "lon"]
```
```{r}
cases_death_by_district_and_date_2_$lat <- location_coord[cases_death_by_district_and_date_2_$Localite, "lat"]
```

```{r}
cases_death_by_district_and_date_2_$categorylower <- tolower(cases_death_by_district_and_date_2_$Category)
```


```{r}
c_wo_national <- cases_death_by_district_and_date_2_                                                           %>% filter(Localite != "National")                                                                          %>% filter(Localite != "National  ")                                                                        %>% filter(Localite != "Mamou")                                                                             %>% filter(Localite != "Lab_")                                                                              %>% filter(Localite != "Kati")                                                                              %>% filter(Localite != "Tougu_")                                                                            %>%  filter(Localite != "Dabola and Djingaraye")                                                            %>% filter(Localite != "For_cariah")
```
```{r}
c_w_death <- c_wo_national %>% filter(Value != "0")
```




```{r}
c_w_national <- cases_death_by_district_and_date_2_ %>%            
                filter(Localite == "National") %>%                                      filter(categorylower == "deaths") 
```
```{r}

```

```{r}
c_w_national$NewDate <- as.Date(c_w_national$Date, format = "%m/%d/%Y")
```

```{r}
c_w_national$Numericdate <- as.numeric(c_w_national$NewDate)
```
```{r}
c_w_national <- c_w_national[-c(571),]
```


```{r}
c_w_national$newvalue <- gsub(",", "", c_w_national$Value)
```

```{r}
c_w_national$Numericvalue <- as.numeric(c_w_national$newvalue)
```
```{r}

```


```{r}
datafordeath <- filter(c_w_death, categorylower == "deaths")
```
```{r}

```
```{r}
datafordeath$NewDate <- as.Date(datafordeath$Date, format = "%m/%d/%Y")
```

```{r}
datafordeath$Numericdate <- as.numeric(datafordeath$NewDate)
```
```{r}
datafordeath$newvalue <- gsub(",", "", datafordeath$Value)
```
```{r}
datafordeath$Value <- as.numeric(datafordeath$newvalue)
```

```{r}
datafordeath$long <- gsub("-122.3400512", "-8.32", datafordeath$long)
datafordeath$lat <- gsub("47.61341", "7.48", datafordeath$lat)
#Lola
```
```{r}
datafordeath$long <- gsub("-63.588653", "-11.73858", datafordeath$long)
datafordeath$lat <- gsub("-16.290154", "7.954042", datafordeath$lat)
```

```{r}
datafordeath$long <- gsub("-77.03918", "-7.74167", datafordeath$long)
datafordeath$lat <- gsub("39.04517", "4.725888", datafordeath$lat)
```

```{r}
datafordeath$long <- gsub("-8.627063", "-12.785352", datafordeath$long)
datafordeath$lat <- gsub("41.167972", "8.768689", datafordeath$lat)

```

```{r}
datafordeath$long <- gsub("-8.6270628", "-12.785352", datafordeath$long)
datafordeath$lat <- gsub("41.167972", "8.768689", datafordeath$lat)

```
```{r}
datafordeath$long <- gsub("-77.0391754", "-7.45", datafordeath$long)
datafordeath$lat <- gsub("39.0451663", "4.45", datafordeath$lat)
#Maryland County 
```
```{r}
datafordeath$long <- gsub("-71.0870977", "-12.39498", datafordeath$long)
datafordeath$lat <- gsub("42.3452395", "11.05912", datafordeath$lat)
#Pita
```
```{r}
#datafordeath$long <- gsub("", "-13.0880556", datafordeath$long)
#datafordeath$lat <- gsub("", "9.4305556", datafordeath$lat)
#For_cariah
```

```{r}
#datafordeath$Localite <- gsub("Port", "Port Loko", datafordeath$Localite)
```

```{r}
datafordeath$long <- as.numeric(datafordeath$long)
datafordeath$lat <- as.numeric(datafordeath$lat)
```



```{r}
datafordeath <- left_join(datafordeath, EbolaGDP, by= c("Country"))
```

```{r}
colnames(datafordeath)[11] <- "Timeline"
```

```{r}
colnames(datafordeath)[14] <- "Household_Size"
```

```{r}
colnames(datafordeath)[16] <- "Percent_Urban"
```

```{r}
colnames(datafordeath)[17] <- "Percent_of_GDP_given_to_Health_Sector"
```

```{r}
colnames(datafordeath)[18] <- "Percent_Using_the_Internet"
```

##############################


###############################
```{r}
c_w_national <- left_join(c_w_national, EbolaGDP, by= c("Country"))
```

###############

```{r}
EbolaGDP$GDP <- gsub(",", "", EbolaGDP$GDP)
```

```{r}
EbolaGDP$GDP <- as.numeric(EbolaGDP$GDP)
```



##################


 
```{r}
c_w_cases <- c_wo_national %>% filter(Category == "Cases")
```


```{r}
c_w_cases$NewDate <- as.Date(c_w_cases$Date, format = "%m/%d/%Y")
```


```{r}
c_w_cases <- c_w_cases %>% filter(Value != "0")
```


```{r}
c_w_cases$Value <- gsub(",", "", c_w_cases$Value)
```


```{r}
c_w_cases$Value <- as.numeric(c_w_cases$Value)
```

```{r}
c_w_cases <- left_join(c_w_cases, EbolaGDP, by= c("Country"))
```





```{r}
colnames(c_w_cases)[11] <- "Timeline"
```

```{r}
colnames(c_w_cases)[12] <- "Household_Size"
```

```{r}
colnames(c_w_cases)[13] <- "GDP"
```

```{r}
colnames(c_w_cases)[14] <- "Percent_Urban"
```

```{r}
colnames(c_w_cases)[15] <- "Percent_of_GDP_given_to_Health_Sector"
```

```{r}
colnames(c_w_cases)[16] <- "Percent_Using_the_Internet"
```


 #########################################
 
 
```{r}
national_cases <- cases_death_by_district_and_date_2_ %>% filter(Localite == "National")  %>%                                  filter(Category == "Cases")
```

```{r}

national_cases$NewDate <- as.Date(national_cases$Date, format = "%m/%d/%Y")

```


```{r}
national_cases$Value <- gsub(",", "", national_cases$Value)
```

```{r}
national_cases$Value <- as.numeric(national_cases$Value)

```

################################################


```{r}
write.table(datafordeath, file = "datafordeathfile")
```

```{r}
write.table(c_w_national, file= "c_w_nationalfile")
```

```{r}
write.table(EbolaGDP, file = "EbolaGDPfile")
```

```{r}
write.table(c_w_cases, file = "c_w_casesfile")
```

```{r}
write.table(national_cases, file = "national_casesfile")
```


#################################

```{r}
uniquedeath <- unique(datafordeath$Localite)
```

```{r}
uniquedeathchart <- matrix(uniquedeath, nrow = 97, ncol = 1)
```


```{r}
library(leaflet)

map <- leaflet() %>% setView(lng = -9.311828, lat = 10.38279, zoom = 4) 

map %>% addTiles() %>% addMarkers(location_coord$lon, location_coord$lat)


 
```

```{r}
leaflet(data = datafordeath) %>% 
     setView(lng = -9.311828, lat = 10.38279, zoom = 4) %>% 
     addTiles() %>% 
     addCircleMarkers(radius = ~Value, label = ~Localite, clusterOptions = markerClusterOptions())
```

```{r}
c_w_national %>% ggplot(aes(NewDate, Numericvalue)) +geom_point(aes(colour=Country))
```


```{r}
ggplot(datafordeath, aes(datafordeath$NewDate, datafordeath$Value)) + geom_point(aes(colour=Localite, alpha=0.5))
```
```{r}
datafordeath %>% ggplot(aes(Timeline, Value)) + geom_point(aes(colour=Localite))

```

```{r}
c_w_national %>% ggplot(aes(Household_Size, Household_Size)) + geom_point(aes(colour=Country))
```

```{r}
c_w_national %>% ggplot(aes(Percent.Urban, Health.as.percent.of.GDP)) + geom_point(aes(size=GDP.x, colour=Country))
```
```{r}
cases_death_by_district_and_date_2_ %>% filter(Localite == "National") %>% ggplot(aes(Date, Value))
```

